encoding: utf-8
baseurl: /catchergames
theme: jekyll-theme-minimal
title: "Catcher Games"
description: "Game development lessons learned and project updates."
author: Holden Rehg
google_analytics: G-19FHKJQ8NE
google_site_verification: i8iGYViNyUMUG8_St0qSAdIYrDcavMZwZpUcBM99HD0
plugins:
  - jekyll-feed
